import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:asn1lib/asn1lib.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:pointycastle/export.dart' show RSAPublicKey;
import 'package:taroshell/core/database/app_database.dart';
import 'package:taroshell/core/utils/crypto_utils.dart';
import 'package:taroshell/core/utils/ssh_key_utils.dart';
import 'package:taroshell/features/keys/data/daos/key_dao.dart';
import 'package:taroshell/features/keys/data/repositories/key_repository_impl.dart';
import 'package:taroshell/features/keys/domain/entities/ssh_key.dart';
import 'package:taroshell/features/keys/domain/repositories/key_repository.dart';
import 'package:taroshell/main.dart';

// =============================================================================
// DAO Provider
// =============================================================================

/// Provides the [KeyDao] instance backed by the application database.
final keyDaoProvider = Provider<KeyDao>((ref) {
  final database = ref.watch(databaseProvider);
  return KeyDao(database);
});

// =============================================================================
// Repository Provider
// =============================================================================

/// Provides the [KeyRepository] implementation with DAO and encryption key
/// injected from the application's root-level providers.
final keyRepositoryProvider = Provider<KeyRepository>((ref) {
  final dao = ref.watch(keyDaoProvider);
  final encryptionKey = ref.watch(encryptionKeyProvider);
  return KeyRepositoryImpl(
    keyDao: dao,
    encryptionKey: encryptionKey,
  );
});

// =============================================================================
// Stream Provider
// =============================================================================

/// Watches all stored SSH keys as a reactive stream.
///
/// UI consumers rebuild automatically when keys are added or removed.
final allKeysProvider = StreamProvider<List<SshKeyEntity>>((ref) {
  final repository = ref.watch(keyRepositoryProvider);
  return repository.watchAllKeys();
});

// =============================================================================
// Action Providers
// =============================================================================

/// Maps the database [KeyType] enum to the [SshKeyAlgorithm] used by the
/// key generation utility.
SshKeyAlgorithm _keyTypeToAlgorithm(KeyType keyType) {
  switch (keyType) {
    case KeyType.rsa2048:
      return SshKeyAlgorithm.rsa2048;
    case KeyType.rsa4096:
      return SshKeyAlgorithm.rsa4096;
    case KeyType.ed25519:
      return SshKeyAlgorithm.ed25519;
  }
}

/// Generates a new SSH key pair in an isolate, encrypts the private key,
/// and persists it to the database.
///
/// Returns the generated [SshKeyEntity] including the public key and
/// fingerprint for display to the user.
final generateKeyProvider =
    FutureProvider.autoDispose.family<SshKeyEntity, GenerateKeyParams>(
  (ref, params) async {
    final repository = ref.read(keyRepositoryProvider);
    final encryptionKey = ref.read(encryptionKeyProvider);

    // Generate the key pair in an isolate to avoid blocking the UI.
    final keyPair = await SshKeyUtils.generateKeyPair(
      algorithm: _keyTypeToAlgorithm(params.keyType),
      comment: params.label,
    );

    // Encrypt the private key before storage. This is a critical security
    // step -- plaintext private keys must never be persisted.
    final encryptedPrivateKey = CryptoUtils.encrypt(
      plaintext: keyPair.privateKeyPem,
      key: encryptionKey,
    );

    final entity = SshKeyEntity(
      id: 0, // Auto-generated by the database.
      label: params.label,
      keyType: params.keyType,
      publicKey: keyPair.publicKeyOpenSsh,
      encryptedPrivateKey: encryptedPrivateKey,
      fingerprint: keyPair.fingerprint,
      createdAt: DateTime.now(),
    );

    final insertedId = await repository.addKey(entity);

    return entity.copyWith(id: insertedId);
  },
);

/// Imports an existing PEM private key from the file system, encrypts it,
/// derives the public key and fingerprint, and stores the result.
///
/// The private key file is read, validated, encrypted, and then stored.
/// The original file on disk is not modified or deleted.
final importKeyProvider =
    FutureProvider.autoDispose.family<SshKeyEntity, ImportKeyParams>(
  (ref, params) async {
    final repository = ref.read(keyRepositoryProvider);
    final encryptionKey = ref.read(encryptionKeyProvider);

    // Read the PEM file from disk.
    final file = File(params.filePath);
    final pemContent = await file.readAsString();

    // Validate that the content looks like a PEM-encoded private key.
    final trimmedPem = pemContent.trim();
    if (!_isValidPemPrivateKey(trimmedPem)) {
      throw const FormatException(
        'The selected file does not contain a valid PEM-encoded private key.',
      );
    }

    // Determine the key type from the PEM header.
    final keyType = _detectKeyTypeFromPem(trimmedPem);

    // Derive public key and fingerprint based on key type.
    String publicKeyOpenSsh;
    String fingerprint;

    if (keyType == KeyType.ed25519) {
      // For Ed25519, the PEM contains seed + public key bytes.
      final keyData = _extractEd25519KeyData(trimmedPem);
      publicKeyOpenSsh = keyData.publicKeyOpenSsh;
      fingerprint = keyData.fingerprint;
    } else {
      // For RSA keys, parse the public components from the PEM directly.
      final rsaPublicKey = _parseRsaPublicKeyFromPem(trimmedPem);
      publicKeyOpenSsh = SshKeyUtils.rsaPublicKeyToOpenSsh(
        rsaPublicKey,
        comment: params.label,
      );
      final publicKeyBlob = _encodeRsaPublicKeyBlob(rsaPublicKey);
      fingerprint = SshKeyUtils.computeFingerprint(publicKeyBlob);
    }

    // Encrypt the private key for secure storage.
    final encryptedPrivateKey = CryptoUtils.encrypt(
      plaintext: trimmedPem,
      key: encryptionKey,
    );

    final entity = SshKeyEntity(
      id: 0, // Auto-generated by the database.
      label: params.label,
      keyType: keyType,
      publicKey: publicKeyOpenSsh,
      encryptedPrivateKey: encryptedPrivateKey,
      fingerprint: fingerprint,
      createdAt: DateTime.now(),
    );

    final insertedId = await repository.addKey(entity);

    return entity.copyWith(id: insertedId);
  },
);

/// Deletes an SSH key by its [id].
final deleteKeyProvider = FutureProvider.autoDispose.family<void, int>(
  (ref, id) async {
    final repository = ref.read(keyRepositoryProvider);
    await repository.deleteKey(id);
  },
);

/// Decrypts a stored private key for use in an SSH connection.
///
/// The returned plaintext PEM should be used immediately and not cached
/// in memory longer than necessary.
final decryptKeyProvider =
    FutureProvider.autoDispose.family<String, String>(
  (ref, encryptedKey) async {
    final repository = ref.read(keyRepositoryProvider);
    return repository.decryptPrivateKey(encryptedKey);
  },
);

// =============================================================================
// Parameter Classes
// =============================================================================

/// Parameters for SSH key generation.
class GenerateKeyParams {
  const GenerateKeyParams({
    required this.label,
    required this.keyType,
  });

  final String label;
  final KeyType keyType;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenerateKeyParams &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          keyType == other.keyType;

  @override
  int get hashCode => Object.hash(label, keyType);
}

/// Parameters for SSH key import.
class ImportKeyParams {
  const ImportKeyParams({
    required this.label,
    required this.filePath,
  });

  final String label;
  final String filePath;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportKeyParams &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          filePath == other.filePath;

  @override
  int get hashCode => Object.hash(label, filePath);
}

// =============================================================================
// Private Helpers
// =============================================================================

/// PEM header patterns for supported private key formats.
const String _pemRsaHeader = '-----BEGIN RSA PRIVATE KEY-----';
const String _pemOpenSshHeader = '-----BEGIN OPENSSH PRIVATE KEY-----';
const String _pemGenericHeader = '-----BEGIN PRIVATE KEY-----';

/// Validates that a string contains a recognised PEM private key header.
bool _isValidPemPrivateKey(String pem) {
  return pem.startsWith(_pemRsaHeader) ||
      pem.startsWith(_pemOpenSshHeader) ||
      pem.startsWith(_pemGenericHeader);
}

/// Detects the [KeyType] from PEM header content.
///
/// Defaults to [KeyType.rsa4096] for generic PKCS#8 keys since the actual
/// bit length cannot be reliably determined from the header alone.
KeyType _detectKeyTypeFromPem(String pem) {
  if (pem.startsWith(_pemOpenSshHeader)) {
    return KeyType.ed25519;
  }
  if (pem.startsWith(_pemRsaHeader)) {
    // Parse the key to determine bit length.
    try {
      final privateKey = SshKeyUtils.parseRsaPrivateKeyPem(pem);
      final bitLength = privateKey.modulus!.bitLength;
      if (bitLength <= 2048) {
        return KeyType.rsa2048;
      }
      return KeyType.rsa4096;
    } catch (_) {
      return KeyType.rsa4096;
    }
  }
  return KeyType.rsa4096;
}

/// Extracts Ed25519 public key and fingerprint from a PEM-encoded key.
_Ed25519KeyData _extractEd25519KeyData(String pem) {
  // Strip PEM armour and decode.
  final lines = pem
      .split('\n')
      .where((line) =>
          line.isNotEmpty &&
          !line.startsWith('-----BEGIN') &&
          !line.startsWith('-----END'))
      .join();
  final keyBytes = base64.decode(lines);

  // Ed25519 PEM from SshKeyUtils contains: [32-byte seed][32-byte public key]
  const seedLength = 32;
  if (keyBytes.length < seedLength * 2) {
    throw const FormatException(
      'Invalid Ed25519 private key: insufficient key data.',
    );
  }

  final publicKeyBytes = Uint8List.sublistView(
    Uint8List.fromList(keyBytes),
    seedLength,
    seedLength * 2,
  );

  // Build OpenSSH public key blob.
  final blobBuilder = BytesBuilder();
  SshKeyUtils.writeString(blobBuilder, 'ssh-ed25519');
  SshKeyUtils.writeBytes(blobBuilder, publicKeyBytes);
  final publicKeyBlob = Uint8List.fromList(blobBuilder.toBytes());

  final base64Public = base64.encode(publicKeyBlob);
  final publicKeyOpenSsh = 'ssh-ed25519 $base64Public';
  final fingerprint = SshKeyUtils.computeFingerprint(publicKeyBlob);

  return _Ed25519KeyData(
    publicKeyOpenSsh: publicKeyOpenSsh,
    fingerprint: fingerprint,
  );
}

class _Ed25519KeyData {
  const _Ed25519KeyData({
    required this.publicKeyOpenSsh,
    required this.fingerprint,
  });

  final String publicKeyOpenSsh;
  final String fingerprint;
}

/// Parses an RSA private key PEM and extracts the public key components
/// (modulus and public exponent) directly from the PKCS#1 ASN.1 structure.
///
/// PKCS#1 RSAPrivateKey format:
///   RSAPrivateKey ::= SEQUENCE {
///     version           INTEGER,  -- 0
///     modulus           INTEGER,  -- n
///     publicExponent    INTEGER,  -- e
///     privateExponent   INTEGER,  -- d
///     prime1            INTEGER,  -- p
///     prime2            INTEGER,  -- q
///     ...
///   }
RSAPublicKey _parseRsaPublicKeyFromPem(String pem) {
  final lines = pem
      .split('\n')
      .where((line) =>
          line.isNotEmpty &&
          !line.startsWith('-----BEGIN') &&
          !line.startsWith('-----END'))
      .join();
  final keyBytes = base64.decode(lines);
  final asn1Parser = ASN1Parser(keyBytes);
  final topSeq = asn1Parser.nextObject() as ASN1Sequence;

  final modulus = (topSeq.elements[1] as ASN1Integer).valueAsBigInteger;
  final publicExponent = (topSeq.elements[2] as ASN1Integer).valueAsBigInteger;

  return RSAPublicKey(modulus, publicExponent);
}

/// Encodes an RSA public key into the OpenSSH binary blob format.
Uint8List _encodeRsaPublicKeyBlob(RSAPublicKey publicKey) {
  final builder = BytesBuilder();
  SshKeyUtils.writeString(builder, 'ssh-rsa');
  SshKeyUtils.writeMpInt(builder, publicKey.publicExponent!);
  SshKeyUtils.writeMpInt(builder, publicKey.modulus!);
  return Uint8List.fromList(builder.toBytes());
}

